version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
hooks:
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 600
      runas: root
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 10
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: root
