#!/bin/bash

which yum >/dev/null 2>/dev/null && {
  yum install -y httpd
  chkconfig httpd on
  exit 0
}

which apt-get >/dev/null 2>/dev/null && {
  apt-get -y install apache2
  rm -f /var/www/html/index.html
  exit 0
}
